### ISSUE TITLE
Black box shows up on crosshair when rendering

### ISSUE THREAD

**Issue by Rellit-219** [yooksi/cocolib#9]
![image](https://user-images.githubusercontent.com/53947335/82086620-9f9e2a80-96a3-11ea-883f-1ac2e7ffbb4c.png)

This black box appears on the crosshair, no matter where you specify the position.

Implementation:

```java
public static final ArrayList<SpriteObject> BAC_HUD_EMPTY_ICONS = new ArrayList<SpriteObject>();
public static final ArrayList<SpriteObject> BAC_HUD_FULL_ICONS = new ArrayList<SpriteObject>();

public static final void initIcons() {
	
	BAC_HUD_EMPTY_ICONS.clear();
	BAC_HUD_FULL_ICONS.clear();
	
	for (int i = 0; i < 9; i++) {
		
		BAC_HUD_EMPTY_ICONS.add(SpriteObject.Builder.create(Defines.MODID, "textures/gui/bac_hud_bar.png").withPos(Alignment.CENTER, 1 + (i * 9) + (i * 3), 10 * i).withUV(0, 0).withSize(9, 9).build());
		BAC_HUD_FULL_ICONS.add(SpriteObject.Builder.create(Defines.MODID, "textures/gui/bac_hud_bar.png").withPos(Alignment.CENTER, 1 + (i * 9) + (i * 3), 10 * i).withUV(9, 0).withSize(9, 9).build());
		
	}
	
}

@SubscribeEvent
public void onPreRenderOverlay(RenderGameOverlayEvent.Pre event) {
	
	@Nullable PlayerController controller = Minecraft.getInstance().playerController;
	
	if (controller != null && controller.gameIsSurvivalOrAdventure()) {
		
		for (SpriteObject empty_bac_icon : BAC_HUD_EMPTY_ICONS) {
			
			GuiElement.bindAndDrawTexture(empty_bac_icon);
			
		}
		
		for (SpriteObject full_bac_icon : BAC_HUD_FULL_ICONS) {
			
			GuiElement.bindAndDrawTexture(full_bac_icon);
			
		}
	}
}
```

**Comment by matshou** [comment]
The issue is most probably caused by missing texture files or incorrect UV coordinates.

Assuming the project is open source, can you show me the location of the textures via link?

**Comment by Rellit-219** [comment]
This is the location for the referenced texture:
https://github.com/boredhero/pv/tree/dev/src/main/resources/assets/vinum/textures/gui

**Comment by matshou** [comment]
The dimensions of valid textures have to be matching powers of two (i.e. `32x32`, `64x64`, `128x128`).

Note that I haven't tested this out so the safest bet would be to use a standard vanilla `256x256` format for textures (which will work) and just pack each texture with as much assets as you can.

**Comment by Rellit-219** [comment]
Will try thanks.

**Comment by Rellit-219** [comment]
Yep that fixed it!
